version: "3.8"
services:
  mysql-db:
    build:
      context: ./db
      dockerfile: dockerfile
    ports:
      - "3306:3306"
    # volumes: # Add persistence of db table data

  spring-backend:
    build:
      context: ./02-backend/rest
      dockerfile: dockerfile
    ports:
      - "8080:8080"
